apiVersion: apps/v1
kind: Deployment
metadata:
  name: desa-consumer-deployment
  labels:
    app: desa
    component: consumer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: desa
      component: consumer
  template:
    metadata:
      annotations:
        kubernetes.io/change-cause: "Initial deployment v0.1.1"
      labels:
        environment: dev
        app: desa
        component: consumer
        version: "0.1.1"
    spec:
      containers:
        - name: desa-consumer-container
          image: dreg1.lab.newpathexchange.com/desa/consumer:v0.1.1
          imagePullPolicy: Always
          args: ["kubernetes"]
          tty: true
          envFrom:
            - configMapRef:
                name: desa-consumer-config
          readinessProbe:
            exec:
              command:
                - /app/k8s_probe.sh
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - /app/k8s_probe.sh
            initialDelaySeconds: 20
            periodSeconds: 10

