apiVersion: v1
kind: ConfigMap
metadata:
  name: desa-producer-config
data:
    # Kafka settings
    KAFKA_BOOTSTRAP_SERVERS: 'desa1:9092,desa2:9092,desa3:9092'
    KAFKA_SECURITY_PROTOCOL: 'SASL_PLAINTEXT'
    KAFKA_SASL_MECHANISM: 'SCRAM-SHA-256'
    KAFKA_SASL_USERNAME: 'app-producer'
    KAFKA_SASL_PASSWORD: 'app123encryptme'
    AVRO_SCHEMA_REGISTRY_URL: 'http://srd1:8081'
    KAFKA_PRODUCER_ACKS: 'all'
    KAFKA_PRODUCER_COMPRESSION: 'none'
    #KAFKA_PRODUCER_COMPRESSION: 'snappy'

    # Application-specific settings
    FAKE_DATA_TOPIC: 'fake_data'
    #SLEEP_SECONDS: '1'
    SLEEP_SECONDS: '.12'

