---

- name: Java prerequisite
  apt:
    name: openjdk-{{ openjdk_version }}-jdk
    state: present
    update_cache: yes
  notify: Restart ZooKeeper

- name: ZooKeeper group
  group:
    name: "{{ zk_group }}"
    gid: 14000
    state: present

- name: ZooKeeper user
  user:
    name: "{{ zk_user }}"
    comment: Zookeeper user
    shell: /bin/bash
    uid: 14000
    group: "{{ zk_group }}"
    state: present

- name: ZooKeeper directories
  file:
    path: "{{ item }}"
    owner: "{{ zk_user }}"
    group: "{{ zk_group }}"
    state: directory
  loop:
    - "{{ zk_data_dir }}"
    - "{{ zk_ver_dir }}"
  notify: Restart ZooKeeper

- name: ZooeKeeper install
  unarchive:
    src: "{{ zk_inst_url }}"
    remote_src: true
    dest: "{{ zk_inst_root }}"
    owner: "{{ zk_user }}"
    group: "{{ zk_group }}"
  notify: Restart ZooKeeper

- name: ZooeKeeper symlink
  file:
    src: "{{ zk_ver_dir }}"
    path: "{{ zk_dir }}"
    owner: "{{ zk_user }}"
    group: "{{ zk_group }}"
    state: link
  notify: Restart ZooKeeper

- name: ZooKeeper config file
  template:
    src: zoo.cfg.j2
    dest: "{{ zk_conf_file }}"
    owner: "{{ zk_user }}"
    group: "{{ zk_group }}"
  notify: Restart ZooKeeper

- name: ZooKeeper node id
  copy:
    content: "{{ groups.zookeeper.index(inventory_hostname)+1 }}"
    dest: "{{ zk_data_dir }}/myid"
    owner: "{{ zk_user }}"
    group: "{{ zk_group }}"
  notify: Restart ZooKeeper

- name: ZooKeeper service file
  template:
    src: zk.service.j2
    dest: "{{ zk_service_file }}"
  notify: Restart ZooKeeper

- name: ZooKeeper service started
  systemd:
    name: zk
    enabled: yes
    masked: no
    daemon_reload: yes
    state: started

