apiVersion: v1
kind: Service
metadata:
  name: desa-exercise-api-service
spec:
  type: NodePort
  selector:
    app: desa
    component: exercise-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080
